@startuml
title диаграмма последовательности
participant Читатель
participant Заявка
participant Управляющий
activate Читатель
Читатель -> Заявка:подает заявку
activate Заявка
Заявка -> Управляющий:выдает заявку
deactivate Читатель
activate Управляющий
Управляющий -> Заявка:оценивает заявку
Заявка -> Управляющий:заявка одобрена
deactivate Заявка
activate Читатель
Управляющий -> Читатель:оценивает читателя
Читатель -> Управляющий:читатель одобрен
Управляющий -> Читатель:выдача или принятие книги
@enduml
