@startuml
left to right direction
title диаграмма развертывания
database Заявка
node Читатель
node Управляющий
Управляющий - Читатель: оценивает
Управляющий - Заявка: оценивает.    
Читатель - Заявка: подает
Управляющий - Читатель: выдает книги
@enduml
